version: "3.8"
services:
  proxy:
    image: nginx:1.20.0
    container_name: django-demo-proxy
    ports:
      - 80:80
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  app:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    image: django/demo
    container_name: django-demo-app
    hostname: django-demo-postgress
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=config.postgres
      # - DJANGO_SETTINGS_MODULE=config.base
    volumes:
       - ./app:/app
  postgres:
    image: postgres:13.2
    container_name: django-demo-postgres
    hostname: django-demo-postgres
    environment:
      - POSTGRES_PASSWORD=postgres